APP:
  RELEASE: false
  ENV: "localhost"
  PORT: ":9090"
 
HTTP_SERVER:
  READ_TIMEOUT: 5s
  WRITE_TIMEOUT: 10s
  IDLE_TIMEOUT: 120s

SWAGGER:
  TITLE: "Stock api dev docs"
  DESCRIPTION: "template API is application to manage stock"
  VERSION: "1.0"
  HOST: "localhost:9090"
  BASE_URL: "/api/v1"
  ENABLE: true
