# These are what we response to our internal services
internal:
  success:
    code: 200
    localization:
      en: "Success."
      th: "สำเร็จ"

  general:
    code: 500
    localization:
      en: "System cannot process this request at the moment. Please try again later."
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"

  bad_request:
    code: 400
    localization:
      en: "System cannot process this request at the moment. Please try again later."
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"
      
  connection_error:
    code: 500
    localization:
      en: "Connection error. Please try again."
      th: "ขออภัย ระบบไม่สามารถดำเนินการได้ในขณะนี้ กรุณาลองใหม่อีกครั้ง"
